apiVersion: apps/v1
kind: Deployment
metadata: 
   name: productcatalogservice
 spec:
   replicas: 2
   selector:
     matchLabels:
       app: productcatalogservice
   template:
     metadata:
       labels:
         app: productcatalogservice
     spec:
       containers:
         - name: productcatalogservice
           image: <Iage_Uri>
           ports:
             - containerPort: 3550
---
 apiVersion: v1
 kind: Service
 metadata:
   name: productcaalogservice
 spec:
   selector:
     app: productcatalogservice
   ports:
     - protocol: TCP
       port: 80
       targetPort: 3550
   type: LoadBalancer
